import { useState, useEffect} from "react";
import { useUser} from '@clerk/nextjs'
import Image from "next/image";
import Head from "next/head";
import Footer from "~/component/footer";
import { Cat, Search, ListFilter, ArrowUpDown, Upload } from "lucide-react"
import Navigation from "~/component/navigationTab";
import PageLoading from "~/component/loadingPage";
import { api } from "~/utils/api";
export default function Adopt(){
  const {isSignedIn} = useUser();
  const [isLoading, setIsLoading] = useState(false);

  const {data: allCats = [],
        isLoading: isCatLoading} = api.cat.getAllCats.useQuery(undefined, {initialData: []});

  useEffect(() => {
    setIsLoading(true);
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);

  // useEffect(() => {
  //   if(allCats === undefined)
  //     return;
  // });

  return(
    <>
      <Head>
        <title>Adopt a Cat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/ava.png"/>
      </Head>

      <main className="h-screen w-screen flex flex-col bg-[#fffbf5] gap-10">
        {isLoading && <PageLoading />}
        <Navigation isSignedIn={isSignedIn}/>
        <div className="flex flex-col items-center gap-6">

          <div className="flex items-center justify-center gap-2">
            <Cat size={50} className="text-[#4c361d] w-6.5 h-6.5"/>
            <span className="text-[32px] font-semibold text-[#4c361d] underline underline-offset-4 decoration-wavy decoration-[#fab24e]">Meet Our Adorable Cats</span>
            <Cat size={50} className="text-[#4c361d] w-6.5 h-6.5"/>
          </div>

          <span className="max-w-6xl text-center text-[20px] text-[#4c361d] px-60">Browse through our loving cats looking for their forever homes. Each cat has a unique story and personality, waiting to bring joy to your life. Click on <a className="font-semibold underline text-[#fab24e] cursor-pointer">a cat&apos;s profile</a> to learn more about them and start the adoption process today!</span>

          <div className="flex items-center gap-2">
            <div className="flex items-center w-100 gap-1 border border-gray-300 bg-white rounded-full px-5 py-2 focus-within:ring-2 focus-within:ring-[#fab24e] transition w-1/3">
              <Search className="h-5 w-5 text-gray-400"/>
              <input
                type="text"
                placeholder="Search cats by name, age, or breed"
                className="w-full outline-none"
              />
            </div>

            <button className="flex items-center gap-2 bg-[#fab24e] text-[15px] text-white px-2.5 py-2 rounded-lg shadow-md hover:bg-[#e6a23c] transition cursor-pointer">
              <ListFilter className="w-4.5 h-4.5"/>
              <span className="font-semibold">Filter</span>
            </button>
            
            <button className="flex items-center gap-2 bg-[#fab24e] text-[15px] text-white px-2.5 py-2 rounded-lg shadow-md hover:bg-[#e6a23c] transition cursor-pointer">
              <ArrowUpDown className="w-4.5 h-4.5"/>
              <span className="font-semibold">Sort</span>
            </button>

            <button className="flex items-center gap-2 bg-[#fab24e] text-[15px] text-white px-2.5 py-2 rounded-lg shadow-md hover:bg-[#e6a23c] transition cursor-pointer">
              <Upload className="w-4.5 h-4.5"/>
              <span className="font-semibold">Upload image</span>
            </button>
          </div>

          {isCatLoading && (<PageLoading/>)}
          {allCats.length === 0 ? (
            <div className="flex flex-col items-center h-full text-[#4c361d] text-[16px] font-medium gap-1">
              <span>Our lovely cats have found their homes!</span>
              <span>Check back soon - we will introduce new whiskered friends shortly. </span>
              <video
                src="/cat-love.mp4"
                autoPlay
                loop
                muted
                playsInline
                className="h-100 w-100 rounded-xl object-cover outline-4 outline-offset-4 outline-dashed outline-[#fab24e] mt-4"
              />

            </div>
          ): (
            <div className="grid sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-6 px-10">
              <span>hello</span>
            </div>
          )}
        </div>
      <Footer/>
      </main>
    </>
  )
}