import {useState, useEffect} from "react";
import PageLoading from "~/component/loadingPage";
import Navigation from "~/component/navigationTab";
import Head from "next/head";
import Image from "next/image";
import Footer from "~/component/footer";

export default function Donate(){
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    setIsLoading(true);
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);

  return(
    <>
      <Head>
        <title>Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/ava.png"/>
      </Head>

      <main className="h-full w-full flex flex-col bg-[#fffbf5] gap-10">
        {isLoading && <PageLoading />}
        <Navigation />

        <div className="flex items-center ml-30 mt-10">
          <Image
            src="/cat_eating.png"
            alt="Cat eating"
            width={700}
            height={300}
            className="w-250 h-125 object-cover"
          />
          <p className="max-w-3xl items-stretch py-20 px-9 -ml-24 text-[30px] font-semibold bg-[#fab24e]">Your donation helps us provide food and shelter for cats in need. Your click, their new beginning.</p>
        </div>

        <p className="ml-30 text-[#4c361d] font-medium text-[22px]"> Make a one-off payment or monthly donation below, or visit our volunteer programs!</p>

        <p className="ml-30 text-[#4c361d] font-semibold text-[45px]">Volunteer programs</p>
        
        <div className="grid grid-cols-4 gap-7 px-30">
          <button className="group flex flex-col items-center text-center gap-3 rounded-lg bg-[#fab24e] p-5 text-[#4c361d] shadow-md transition duration-300 hover:bg-white focus-visible:ring-2 focus-visible:ring-amber-500">
            <p className="font-bold">Wednesday night</p>

            <div className="relative w-72 h-36 rounded-lg bg-white overflow-hidden grid place-items-center">
              <Image
                src="/cat-sleep.png"
                alt="Cat sleeping"
                fill
                className="object-contain"
                sizes="144px"
                priority
              />
            </div>

            <p className="text-[15px] font-semibold">The weekly dinner for our lovely stray cats</p>
            <p className="text-[15px] font-normal">
              Do you want to join us and help feeding stray cats in your neighborhood? Click here to find out!
            </p>
          </button>

          <button className="group flex flex-col items-center text-center gap-3 rounded-lg bg-[#fab24e] p-5 text-[#4c361d] shadow-md transition duration-300 hover:bg-white focus-visible:ring-2 focus-visible:ring-amber-500">
            <p className="font-bold">Halloween Special Day</p>

            <div className="relative w-72 h-36 rounded-lg bg-white overflow-hidden grid place-items-center">
              <Image
                src="/cat_7.png"
                alt="Halloween cat"
                fill
                className="object-contain"
                sizes="144px"
                priority
              />
            </div>

            <p className="text-[15px] font-semibold">Costumes, treats & donation drive.</p>
            <p className="text-[15px] font-normal">
              Do you want to connect and have fun with other cat lovers? Click here to find out!
            </p>
          </button>

          <button className="group flex flex-col items-center text-center gap-3 rounded-lg bg-[#fab24e] p-5 text-[#4c361d] shadow-md transition duration-300 hover:bg-white focus-visible:ring-2 focus-visible:ring-amber-500">
            <p className="font-bold">Weekend Adoption Help</p>

            <div className="relative w-72 h-36 rounded-lg bg-white overflow-hidden grid place-items-center">
              <Image
                src="/cat_6.png"
                alt="Cat fish"
                fill
                className="object-contain"
                sizes="144px"
                priority
              />
            </div>

            <p className="text-[15px] font-semibold">Meet cats, chat with adopters.</p>
            <p className="text-[15px] font-normal">
              Do you want to help cats find their forever homes? Click here to find out!
            </p>
          </button>

          <button className="group flex flex-col items-center text-center gap-3 rounded-lg bg-[#fab24e] p-5 text-[#4c361d] shadow-md transition duration-300 hover:bg-white focus-visible:ring-2 focus-visible:ring-amber-500">
            <p className="font-bold">TNR Clinic Crew</p>

            <div className="relative w-72 h-36 rounded-lg bg-white overflow-hidden grid place-items-center">
              <Image
                src="/cat_8.png"
                alt="Cat cute"
                fill
                className="object-contain"
                sizes="144px"
                priority
              />
            </div>

            <p className="text-[15px] font-semibold">Trap–Neuter–Return support</p>
            <p className="text-[15px] font-normal">
              Do you want to join us and help with TNR efforts in your neighborhood? Click here to find out!
            </p>
          </button>
        </div>

        <div className="ml-30 mt-10 flex flex-col gap-4 text-[25px] font-medium text-[#674c2f]">
          <p className="font-semibold text-[45px] text-[#4c361d]">Donate via</p>
          <p>Clementine Cats</p>
          <p>BSB: XXX-XXX</p>
          <p>Account: XXXX-XXXXX</p>
        </div>

        <div className="ml-30 mt-10 flex flex-col gap-4 text-[25px] font-medium text-[#674c2f]">
          <p className="font-semibold text-[45px] text-[#4c361d]">Donate items</p>
          <p>Visit our FAQs to check what items we really need.</p>
        </div>

      </main>

      <div className="bg-[#4c361d] flex flex-col text-white font-medium p-20 mt-20 items-center gap-2">
          <p className="text-[30px]">Thank you for your support!</p>
          <p className="text-[20px] ">Your donation makes a difference in the lives of cats in need.</p>
        </div>

      <Footer />

    </>
  )
}