import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { ChevronRight } from "lucide-react";
import { useRouter } from "next/router";
import { SignInButton,
          SignedOut,
          useUser} from '@clerk/nextjs'

import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Clementine Cats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/ava.png"/>
      </Head>

      <div className="flex items-center justify-between p-3 bg-[#fab24e]">
        <div className="flex items-center gap-5">
          <div className="flex items-center gap-2">
            <Image
              src="/ava.png"
              alt="Clementine Cat Logo"
              className="rounded-full"
              width={40}
              height={40}
            />
            <span className="text-[20px] font-medium"> Clementine Cat</span>
          </div>

          <div className="flex justify-center text-[15px] gap-2">
            <Link
              href="/home"
              className="flex items-center font-medium hover:text-gray-700 hover:underline cursor-pointer"
            >
              <span>Home</span>
              <ChevronRight className="ml-1 h-3 w-3 shrink-0" />
            </Link>

            <Link
              href="/donate"
              className="flex items-center font-medium hover:text-gray-700 hover:underline cursor-pointer"
            >
              <span>Donate</span>
              <ChevronRight className="ml-1 h-3 w-3 shrink-0" />
            </Link>

            <Link
              href="/adopt"
              className="flex items-center font-medium hover:text-gray-700 hover:underline cursor-pointer"
            >
              <span>Adopt</span>
              <ChevronRight className="ml-1 h-3 w-3 shrink-0" />
            </Link>

            <Link
              href="/contact"
              className="flex items-center font-medium hover:text-gray-700 hover:underline cursor-pointer"
            >
              <span>Contact</span>
              <ChevronRight className="ml-1 h-3 w-3 shrink-0" />
            </Link>

            <Link
              href="/information"
              className="flex items-center font-medium hover:text-gray-700 hover:underline cursor-pointer"
            >
              <span>About us</span>
              <ChevronRight className="ml-1 h-3 w-3 shrink-0" />
            </Link>
          </div>
        </div>

        <div className="flex items-center -mb-7 mr-70">
          <Image
            src="/cat-sleep.png"
            alt="Cat sleeping"
            width={200}
            height={200}
          />
        </div>

        <div className="flex items-center gap-2">
            <SignedOut>
              <SignInButton mode="modal">
                <button className="text-[15px] text-white font-medium rounded-xl px-3 py-2 bg-black hover:bg-gray-700 hover:text-white cursor-pointer">
                  Sign up
                </button>
              </SignInButton>
              <SignInButton mode="modal">
                <button className="text-[15px] font-medium rounded-xl px-3 py-2 bg-white hover:bg-gray-100 hover:text-gray-800 cursor-pointer">
                  Log in
                </button>
              </SignInButton>
            </SignedOut>
          </div>
      </div>

      {/* <main className="flex flex-1 items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-bold">Welcome to Clementine Cats</h1>
          <p className="text-lg text-center">
            Your one-stop solution for adopting and caring for cats.
          </p>
        </div>
      </main> */}
    </>
  );
}
