import Head from "next/head";
import Image from "next/image";
import { Search, Play, PawPrint } from "lucide-react";
import { useRouter } from "next/router";
import { useUser} from '@clerk/nextjs'
import { useEffect } from "react";
import PageLoading from "~/component/loadingPage";
import CatCarousel from "~/component/carousel";
import Navigation from "~/component/navigationTab";
import Footer from "~/component/footer";

export default function Home() {
  const router = useRouter();
  const { isLoaded, isSignedIn } = useUser();

  useEffect(() => {
    if (!isLoaded && router.pathname === "/"){
      <PageLoading />
    }
    if (isSignedIn && router.pathname === "/"){
      void router.push("/adopt");
    }
  }, [isSignedIn, isLoaded, router]);

  return (
    <>
      <Head>
        <title>Clementine Cats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/ava.png"/>
      </Head>

      <Navigation isSignedIn={false} />

      <main className="relative min-h-screen flex flex-row items-center justify-between bg-[#fffbf5] 
            bg-[url('/bg.png')] bg-no-repeat bg-cover px-12">

        <div className="flex-1 flex flex-col items-center text-center gap-6">
          <div className="flex flex-wrap items-baseline text-[60px] font-bold gap-2">
            <h1>Looking for a</h1>
            <h1 className="text-[#fab24e]">feline</h1>
            <h1 >friend?</h1>
          </div>

          <p className="max-w-xl text-[20px] font-normal leading-relaxed text-gray-700">
            Helping cats find loving families — whether you&apos;re after a playful kitten
            or a calm companion, your purr-fect match is just a click away!.
          </p>

          <div className="box-border p-8 border-2 border-gray-300 rounded-md shadow-md bg-white/60 flex items-center gap-10 text-gray-700">
            <div className="flex flex-col">
              <span className="font-medium">76</span>
              <span className="text-[15px]">Waiting for homes</span>
            </div>
            <div className="flex flex-col">
              <span className="font-medium">180</span>
              <span className="text-[15px]">Adopted last year</span>
            </div>
            <div className="flex flex-col">
              <span className="font-medium">200</span>
              <span className="text-[15px]">Rescued</span>
            </div>
          </div>

          <button className="flex items-center gap-3 px-4 py-3 bg-[#fab24e] text-white font-medium rounded-full hover:bg-amber-600">
            <Play className="h-5 w-5" />
            <span className="text-[17px] font-medium">Get started</span>
          </button>
        </div>

        <div className="flex-1 flex flex-col items-center text-center gap-6">
          <div role="search" className="w-full max-w-[360px] mx-auto">
            <div className="flex items-center border border-gray-300 bg-white rounded-full px-5 py-2.5 w-full focus-within:ring-2 focus-within:ring-[#fab24e]">
              <Search className="h-5 w-5 text-gray-400 mr-2" />
              <input
                type="text"
                placeholder="Search for cats by breed, age, or location"
                className="w-full outline-none"
              />
            </div>
          </div>

          <div className="w-full max-w-[360px] mx-auto">
            <CatCarousel />
          </div>
        </div>
      </main>

      <section className="relative bg-white py-16">
        <div className="mx-auto max-w-6xl px-6 grid md:grid-cols-2 gap-10 items-center">
          <div className="relative">
            <div className="absolute inset-0 -z-10 rounded-3xl bg-gradient-to-br from-amber-100/70 via-white to-transparent blur-2xl" />
            <Image
              src="/texudo.png"
              alt="Tuxedo cat"
              width={420}
              height={360}
              className="h-auto w-auto drop-shadow-xl"
              priority={false}
            />
          </div>

          <div className="text-gray-700">
            <h2 className="text-2xl md:text-3xl font-semibold text-gray-900 tracking-tight">
              Do you know these tips to take care of a rescue cat?
            </h2>

            <ul className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                {
                  title: "Set up a safe room",
                  body: "Quiet space with bed, litter box, water, and a hiding spot.",
                },
                {
                  title: "Go slow",
                  body: "Introduce rooms & people gradually, let the cat set the pace.",
                },
                {
                  title: "Vet within 7 days",
                  body: "Health check, parasite control, update microchip details.",
                },
                {
                  title: "Steady meals",
                  body: "Fixed schedule, transition food over 5–7 days to avoid upsets.",
                },
                {
                  title: "Litter rule",
                  body: "1 box per cat + 1 scoop daily, unscented clumping litter.",
                },
                {
                  title: "Scratching posts",
                  body: "Place near sleeping spots/doorways, reward scratching there.",
                },
                {
                  title: "Play & enrich",
                  body: "2×10–15 min wand-toy sessions, add perches & window views.",
                },
                {
                  title: "Pet-proof",
                  body: "Secure windows, hide cords, remove toxic plants & tiny items.",
                },
              ].map((tip) => (
                <li key={tip.title} className="flex items-start gap-3">
                  <PawPrint className="mt-1 text-amber-600"/>
                  <div>
                    <p className="font-medium text-gray-900">{tip.title}</p>
                    <p className="text-sm text-gray-600">{tip.body}</p>
                  </div>
                </li>
              ))}
            </ul>

            <div className="mt-6 flex flex-wrap gap-2">
              {["First-week checklist", "Vet visit", "Feeding plan", "Litter setup", "Enrichment"].map(
                (t) => (
                  <span
                    key={t}
                    className="px-2.5 py-1 rounded-full text-xs font-medium bg-amber-50 text-amber-700 border border-amber-200"
                  >
                    {t}
                  </span>
                ),
              )}
            </div>
          </div>
        </div>
      </section>

      <section className="bg-[#fffbf5] py-16">
        <div className="mx-auto max-w-6xl px-6 text-center">
          <h2 className="text-2xl md:text-3xl font-semibold text-gray-900 tracking-tight">
            Clementine Cats Newsletter
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-6">
            <div className="flex flex-col items-start border border-gray-300 rounded-lg p-6 bg-white text-left">
              <h3 className="text-lg font-medium text-gray-900 mb-3">Stay Updated!</h3>
              <p className="text-gray-700 mb-4">Subscribe to our newsletter for the latest cat adoption stories, tips, and events.</p>
            </div>

            <div className="flex flex-col items-start border border-gray-300 rounded-lg p-6 bg-white text-left">
              <h3 className="text-lg font-medium text-gray-900 mb-3">Stay Updated!</h3>
              <p className="text-gray-700 mb-4">Subscribe to our newsletter for the latest cat adoption stories, tips, and events.</p>
            </div>

            <div className="flex flex-col items-start border border-gray-300 rounded-lg p-6 bg-white text-left">
              <h3 className="text-lg font-medium text-gray-900 mb-3">Stay Updated!</h3>
              <p className="text-gray-700 mb-4">Subscribe to our newsletter for the latest cat adoption stories, tips, and events.</p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
